# This YAML contains various marker colors and shapes for the three plotting schemes
# Changes here will be applied to notebook plotting immediately (after restarting the kernel)

obs_c: {
    "ao": "#40C3C3",
    "arecibo": "#40C3C3" ,
    "gbt": "#61C853",
    "vla": "#40635F",
    "CHIME": "#A3DB8B",
    "nancay": "#407BD5",
    "ncyobs": "#407BD5",
    "effelsberg_asterix": "#00A9E2",
    "effelsberg": "#00A9E2",
    "leap": "#004B97",
    "jodrell": "#404BD5",
    "jbroach": "#404BD5",
    "wsrt": "#404B97",
    "parkes": "#BE0119",
    "gmrt": "#855CA0",
    "meerkat": "#FD9927",
    "fast": "#FD99CA",
    "nenufar": "#E0DEFF", 
    "lofar": "#E0EAFF",
    "None": "#808080",
}

pta_c: {
    "InPTA": "#855CA0",
    "EPTA": "#407BD5",
    "NANOGrav": "#61C853",
    "PPTA": "#BE0119",
    "MPTA": "#FD9927",
    "CPTA": "#FD99CA",
    "None": "#808080",
}

febe_c: {
    "327_ASP": "#6BA9E2",
    "327_PUPPI": "#6BA9E2",
    "430_ASP": "#6BA9E2",
    "430_PUPPI": "#6BA9E2",
    "L-wide_ASP": "#6BA9E2",
    "L-wide_PUPPI": "#6BA9E2",
    "Rcvr1_2_GASP": "#61C853",
    "Rcvr1_2_GUPPI": "#61C853",
    "Rcvr1_2_VEGAS": "hotpink",
    "Rcvr_800_GASP": "#61C853",
    "Rcvr_800_GUPPI": "#61C853",
    "Rcvr_800_VEGAS": "violet",
    "S-wide_ASP": "#6BA9E2",
    "S-wide_PUPPI": "#6BA9E2",
    "1.5GHz_YUPPI": "#40635F",
    "3GHz_YUPPI": "#40635F",
    "6GHz_YUPPI": "#40635F",
    "CHIME": "#ECE133",
    "unknown_LEAP": "#FD9927",
    "NRT.BON.1600": "#FD9927",
    "NRT.BON.1400": "#FD9927",
    "NRT.BON.2000": "#FD9927",
    "NRT.NUPPI.1484": "#FD9927",
    "NRT.NUPPI.1854": "#FD9927",
    "NRT.NUPPI.2154": "#FD9927",
    "NRT.NUPPI.2539": "#FD9927",
    "EFF.EBPP.1360": "#855CA0",
    "EFF.EBPP.1410": "#855CA0",
    "EFF.EBPP.2639": "#855CA0",
    "S60-2_asterix": "#855CA0",
    "JBO.DFB.1400": "#407BD5",
    "JBO.DFB.1520": "#407BD5",
    "WSRT.P2.1380": "#E5A4CB",
    "WSRT.P1.1380.C": "#E5A4CB",
    "WSRT.P1.2273.C": "#E5A4CB",
    "WSRT.P1.323.C": "#40635F",
    "WSRT.P1.367.C": "#40635F",
    "P217-3_asterix": "#855CA0",
    "unknown_asterix": "#855CA0",
    "P200-3_asterix": "#855CA0",
    "P217-3_PuMa2": "#855CA0",
    "P217-6_LEAP": "#855CA0",
    "P217-3_LEAP": "#855CA0",
    "R217-3_LEAP": "#855CA0",
    "P200-3_LEAP": "#855CA0",
    "JBO.ROACH.1620": "#407BD5",
    "1050CM_PDFB4": "#BE0119",
    "1050CM_PDFB1": "#BE0119",
    "1050CM_PDFB2": "#BE0119",
    "1050CM_PDFB3": "#BE0119",
    "1050CM_WBCORR": "#BE0119",
    "1050CM_CPSR2": "#BE0119",
    "1050CM_CASPSR": "#BE0119",
    "MULTI_CPSR2m": "#BE0119",
    "MULTI_PDFB1": "#BE0119",
    "H-OH_PDFB1": "#BE0119",
    "H-OH_CPSR2n": "#BE0119",
    "H-OH_CPSR2m": "#BE0119",
    "H-OH_PDFB4": "#BE0119",
    "MULTI_CPSR2m": "#BE0119",
    "MULTI_CPSR2n": "#BE0119",
    "MULTI_WBCORR": "#BE0119",
    "MULTI_PDFB2": "#BE0119",
    "MULTI_PDFB3": "#BE0119",
    "MULTI_PDFB4": "#BE0119",
    "UWL_Medusa": "#BE0119",
    "UWL_CASPSR": "#BE0119",
    "UWL_PDFB4": "#BE0119",
    "UWL_PDFB4_10CM": "#BE0119",
    "UWL_PDFB4_40CM": "#BE0119",
    "None": "#808080",
    "unknown_asterix": "#855CA0",
    "CHIME": "#A3DB8B",
    "unknown_LuMP": "#E0EAFF",
    "unknown_COBALT": "#E0EAFF",
    "unknown_LOFAR": "#E0EAFF",
    "LaNewBa_LUPPI": "#E0DEFF",
    "19BEAM_MB4K": "#FD99CA",
}

ng20_c: {
    "CHIME": "#FFA733",
    "327_ASP": "#BE0119",
    "327_PUPPI": "#BE0119",
    "430_ASP": "#FD9927",
    "430_PUPPI": "#FD9927",
    "L-wide_ASP": "#BDB6F6",
    "L-wide_PUPPI": "#BDB6F6",
    "Rcvr1_2_GASP": "#79A3E2",
    "Rcvr1_2_GUPPI": "#79A3E2",
    "Rcvr1_2_VEGAS": "#79A3E2",
    "Rcvr_800_GASP": "#8DD883",
    "Rcvr_800_GUPPI": "#8DD883",
    "Rcvr_800_VEGAS": "#8DD883",
    "S-wide_ASP": "#C4457A",
    "S-wide_PUPPI": "#C4457A",
    "1.5GHz_YUPPI": "#EBADCB",
    "3GHz_YUPPI": "#E79CC1",
    "6GHz_YUPPI": "#DB6BA1",
}

obs_m: {
    "ao": "x",
    "arecibo": "x",
    "gbt": "x",
    "vla": "x",
    "CHIME": "x",
    "leap": "x",
    "nancay": "x",
    "ncyobs": "x",
    "effelsberg_asterix": "x",
    "effelsberg": "x",
    "jodrell": "x",
    "jbroach": "x",
    "wsrt": "x",
    "parkes": "x",
    "gmrt": "x",
    "meerkat": "x",
    "fast": "x",
    "lofar": "x",
    "nenufar": "x",
    "None": "x",
}

pta_m: {
    "InPTA": "x",
    "EPTA": "x",
    "NANOGrav": "x",
    "PPTA": "x",
    "MPTA": "x",
    "CPTA": "x",
    "None": "x",
}

ng20_m: {
    "327_ASP": "x",
    "327_PUPPI": "x",
    "430_ASP": "x",
    "430_PUPPI": "x",
    "L-wide_ASP": "x",
    "L-wide_PUPPI": "x",
    "Rcvr1_2_GASP": "x",
    "Rcvr1_2_GUPPI": "x",
    "Rcvr1_2_VEGAS": "x",
    "Rcvr_800_GASP": "x",
    "Rcvr_800_GUPPI": "x",
    "Rcvr_800_VEGAS": "x",
    "S-wide_ASP": "x",
    "S-wide_PUPPI": "x",
    "1.5GHz_YUPPI": "x",
    "3GHz_YUPPI": "x",
    "6GHz_YUPPI": "x",
    "CHIME": "x",
}

febe_m: {
    "327_ASP": "x",
    "327_PUPPI": "x",
    "430_ASP": "x",
    "430_PUPPI": "x",
    "L-wide_ASP": "x",
    "L-wide_PUPPI": "x",
    "Rcvr1_2_GASP": "x",
    "Rcvr1_2_GUPPI": "x",
    "Rcvr1_2_VEGAS": "x",
    "Rcvr_800_GASP": "o",
    "Rcvr_800_GUPPI": "o",
    "Rcvr_800_VEGAS": "o",
    "S-wide_ASP": "o",
    "S-wide_PUPPI": "o",
    "1.5GHz_YUPPI": "x",
    "3GHz_YUPPI": "o",
    "6GHz_YUPPI": "^",
    "CHIME": "x",
    "NRT.BON.1600": "x",
    "NRT.BON.1400": "o",
    "NRT.BON.2000": "^",
    "NRT.NUPPI.1484": "x",
    "NRT.NUPPI.1854": "o",
    "NRT.NUPPI.2154": "^",
    "NRT.NUPPI.2539": "^",
    "EFF.EBPP.1360": "o",
    "EFF.EBPP.1410": "x",
    "EFF.EBPP.2639": "^",
    "S60-2_asterix": "v",
    "P217-3_asterix": "x",
    "P200-3_asterix": "v",
    "unknown_asterix": "v",
    "P217-3_PuMa2": "x",
    "P200-3_LEAP": "v",
    "P217-6_LEAP": "x",
    "P217-3_LEAP": "x",
    "R217-3_LEAP": "x",
    "unknown_LEAP": "x",
    "JBO.DFB.1400": "x",
    "JBO.DFB.1520": "o",
    "JBO.ROACH.1620": "^",
    "WSRT.P2.1380": "v",
    "WSRT.P1.1380.C": "x",
    "WSRT.P1.2273.C": "o",
    "WSRT.P1.323.C": "x",
    "WSRT.P1.367.C": "x",
    "1050CM_PDFB4": "x",
    "1050CM_PDFB1": "x",
    "1050CM_PDFB2": "x",
    "1050CM_PDFB3": "x",
    "1050CM_WBCORR": "x",
    "1050CM_CPSR2": "x",
    "1050CM_CPSR2m": "x",
    "1050CM_CASPSR": "x",
    "MULTI_CPSR2m": "o",
    "MULTI_PDFB1": "o",
    "H-OH_PDFB1": "^",
    "H-OH_CPSR2m": "^",
    "H-OH_CPSR2n": "^",
    "H-OH_PDFB4": "^",
    "MULTI_CPSR2n": "o",
    "MULTI_WBCORR": "o",
    "MULTI_PDFB2": "o",
    "MULTI_PDFB3": "o",
    "MULTI_PDFB4": "o",
    "UWL_Medusa": "v",
    "UWL_PDFB4": "v",
    "UWL_PDFB4_10CM": "v",
    "UWL_PDFB4_40CM": "v",
    "UWL_CASPSR": "v",
    "None": "x",
    "3GHz_YUPPI": "x",
    "6GHz_YUPPI": "x",
    "CHIME": "x",
    "19BEAM_MB4K": "x", 
}

label_names: {
    "327_ASP": "ASP 327 MHz",
    "327_PUPPI": "PUPPI 327 MHz",
    "430_ASP": "ASP 430 MHz",
    "430_PUPPI": "PUPPI 430 MHz",
    "L-wide_ASP": "ASP L-wide",
    "L-wide_PUPPI": "PUPPI L-wide",
    "Rcvr1_2_GASP": "GASP L-band",
    "Rcvr1_2_GUPPI": "GUPPI L-band",
    "Rcvr1_2_VEGAS": "VEGAS L-band",
    "Rcvr_800_GASP": "GASP 820 MHz",
    "Rcvr_800_GUPPI": "GUPPI 820 MHz",
    "Rcvr_800_VEGAS": "VEGAS 820 MHz",
    "S-wide_ASP": "ASP S-wide",
    "S-wide_PUPPI": "PUPPI S-wide",
    "1.5GHz_YUPPI": "YUPPI 1.5 GHz",
    "3GHz_YUPPI": "YUPPI 3 GHz",
    "6GHz_YUPPI": "YUPPI 6 GHz",
    "CHIME": "CHIME",
}
