name: Bind Reports to Pull Request

# Triggered by the name of the previous workflow
on:
  workflow_run:
    workflows: ["Notebook Pipeline (Ubuntu)"]
    types: [completed]

permissions:
  actions: read
  contents: read
  pull-requests: write # needed to post comments

jobs:
  build:
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: .github/scripts
          persist-credentials: false

      - uses: actions/github-script@v9
        with:
          script: |
            const commentArtifacts = require('./.github/scripts/comment-artifacts.js')
            await commentArtifacts({ github, context, core });
